export const categoriesForConversionArray = [
  'COMERCIAL / ASSISTÊNCIA SOCIAL',
  'COMERCIAL / ESPECIAL',
  'COMERCIAL / NORMAL',
  'INDUSTRIAL / NORMAL',
  'PUBLICO / COM CONTRATO DE PROGRAMA',
  'PUBLICO / COM CONTRATO (PURA)',
  'PUBLICO / NORMAL',
  'RESIDENCIAL / ESPECIAL',
  'RESIDENCIAL / NORMAL',
  'RESIDENCIAL / SOCIAL',
  'RESIDENCIAL / VULNERAVEL NORMAL',
]

export const categoriesForConversionEnum = {
  EMPTY: '',
  COMMERCIAL_SOCIAL_ASSISTANCE: 'COMERCIAL / ASSISTÊNCIA SOCIAL',
  COMMERCIAL_NORMAL: 'COMERCIAL / NORMAL',
  INDUSTRIAL_NORMAL: 'INDUSTRIAL / NORMAL',
  PUBLIC_WITH_PROGRAM_AGREEMENT: 'PUBLICO / COM CONTRATO DE PROGRAMA',
  PUBLIC_WITH_CONTRACT_PURE: 'PUBLICO / COM CONTRATO (PURA)',
  PUBLIC_NORMAL: 'PUBLICO / NORMAL',
  RESIDENTIAL_NORMAL: 'RESIDENCIAL / NORMAL',
  RESIDENTIAL_SOCIAL: 'RESIDENCIAL / SOCIAL',
  RESIDENTIAL_VULNERABLE_NORMAL: 'RESIDENCIAL / VULNERAVEL NORMAL',
}
