export const categoriesForConversionArray = [
  'COMERCIAL / ASSISTÊNCIA SOCIAL',
  'COMERCIAL / ESPECIAL',
  'COMERCIAL / NORMAL',
  'INDUSTRIAL / NORMAL',
  'PUBLICO / COM CONTRATO DE PROGRAMA',
  'PUBLICO / COM CONTRATO (PURA)',
  'PUBLICO / NORMAL',
  'RESIDENCIAL / ESPECIAL',
  'RESIDENCIAL / NORMAL',
  'RESIDENCIAL / SOCIAL',
  'RESIDENCIAL / VULNERAVEL NORMAL',
]
