// Database
export const ADMIN_ACCOUNT_TYPE = 'ADMIN'
export const CUSTOMER_ACCOUNT_TYPE = 'CUSTOMER'
export const AVATAR_FILE_UPLOAD_FIELD = 'avatar_file'
export const NEWS_IMAGE_FILE_UPLOAD_FIELD = 'image_file'

// HTTP status code
export const HTTP_STATUS_CODE = {
  SUCCESS_DEFAULT: 200,
  CREATED: 201,
  ERROR_DEFAULT: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
}
